// Code generated by "stringer -type=garbanzoType"; DO NOT EDIT.

package persistence

import "fmt"

const _garbanzoType_name = "DESIKABULI"

var _garbanzoType_index = [...]uint8{0, 4, 10}

func (i garbanzoType) String() string {
	i -= 1001
	if i < 0 || i >= garbanzoType(len(_garbanzoType_index)-1) {
		return fmt.Sprintf("garbanzoType(%d)", i+1001)
	}
	return _garbanzoType_name[_garbanzoType_index[i]:_garbanzoType_index[i+1]]
}
