// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package garbanzo_test

import (
	"context"
	"time"

	"github.com/myshkin5/effective-octo-garbanzo/persistence/data"
	"github.com/satori/go.uuid"
)

type mockGarbanzoService struct {
	FetchAllGarbanzosCalled chan bool
	FetchAllGarbanzosInput  struct {
		Ctx chan context.Context
	}
	FetchAllGarbanzosOutput struct {
		Garbanzos chan []data.Garbanzo
		Err       chan error
	}
	FetchGarbanzoByAPIUUIDCalled chan bool
	FetchGarbanzoByAPIUUIDInput  struct {
		Ctx     chan context.Context
		ApiUUID chan uuid.UUID
	}
	FetchGarbanzoByAPIUUIDOutput struct {
		Garbanzo chan data.Garbanzo
		Err      chan error
	}
	CreateGarbanzoCalled chan bool
	CreateGarbanzoInput  struct {
		Ctx        chan context.Context
		GarbanzoIn chan data.Garbanzo
	}
	CreateGarbanzoOutput struct {
		GarbanzoOut chan data.Garbanzo
		Err         chan error
	}
	DeleteGarbanzoByAPIUUIDCalled chan bool
	DeleteGarbanzoByAPIUUIDInput  struct {
		Ctx     chan context.Context
		ApiUUID chan uuid.UUID
	}
	DeleteGarbanzoByAPIUUIDOutput struct {
		Err chan error
	}
}

func newMockGarbanzoService() *mockGarbanzoService {
	m := &mockGarbanzoService{}
	m.FetchAllGarbanzosCalled = make(chan bool, 100)
	m.FetchAllGarbanzosInput.Ctx = make(chan context.Context, 100)
	m.FetchAllGarbanzosOutput.Garbanzos = make(chan []data.Garbanzo, 100)
	m.FetchAllGarbanzosOutput.Err = make(chan error, 100)
	m.FetchGarbanzoByAPIUUIDCalled = make(chan bool, 100)
	m.FetchGarbanzoByAPIUUIDInput.Ctx = make(chan context.Context, 100)
	m.FetchGarbanzoByAPIUUIDInput.ApiUUID = make(chan uuid.UUID, 100)
	m.FetchGarbanzoByAPIUUIDOutput.Garbanzo = make(chan data.Garbanzo, 100)
	m.FetchGarbanzoByAPIUUIDOutput.Err = make(chan error, 100)
	m.CreateGarbanzoCalled = make(chan bool, 100)
	m.CreateGarbanzoInput.Ctx = make(chan context.Context, 100)
	m.CreateGarbanzoInput.GarbanzoIn = make(chan data.Garbanzo, 100)
	m.CreateGarbanzoOutput.GarbanzoOut = make(chan data.Garbanzo, 100)
	m.CreateGarbanzoOutput.Err = make(chan error, 100)
	m.DeleteGarbanzoByAPIUUIDCalled = make(chan bool, 100)
	m.DeleteGarbanzoByAPIUUIDInput.Ctx = make(chan context.Context, 100)
	m.DeleteGarbanzoByAPIUUIDInput.ApiUUID = make(chan uuid.UUID, 100)
	m.DeleteGarbanzoByAPIUUIDOutput.Err = make(chan error, 100)
	return m
}
func (m *mockGarbanzoService) FetchAllGarbanzos(ctx context.Context) (garbanzos []data.Garbanzo, err error) {
	m.FetchAllGarbanzosCalled <- true
	m.FetchAllGarbanzosInput.Ctx <- ctx
	return <-m.FetchAllGarbanzosOutput.Garbanzos, <-m.FetchAllGarbanzosOutput.Err
}
func (m *mockGarbanzoService) FetchGarbanzoByAPIUUID(ctx context.Context, apiUUID uuid.UUID) (garbanzo data.Garbanzo, err error) {
	m.FetchGarbanzoByAPIUUIDCalled <- true
	m.FetchGarbanzoByAPIUUIDInput.Ctx <- ctx
	m.FetchGarbanzoByAPIUUIDInput.ApiUUID <- apiUUID
	return <-m.FetchGarbanzoByAPIUUIDOutput.Garbanzo, <-m.FetchGarbanzoByAPIUUIDOutput.Err
}
func (m *mockGarbanzoService) CreateGarbanzo(ctx context.Context, garbanzoIn data.Garbanzo) (garbanzoOut data.Garbanzo, err error) {
	m.CreateGarbanzoCalled <- true
	m.CreateGarbanzoInput.Ctx <- ctx
	m.CreateGarbanzoInput.GarbanzoIn <- garbanzoIn
	return <-m.CreateGarbanzoOutput.GarbanzoOut, <-m.CreateGarbanzoOutput.Err
}
func (m *mockGarbanzoService) DeleteGarbanzoByAPIUUID(ctx context.Context, apiUUID uuid.UUID) (err error) {
	m.DeleteGarbanzoByAPIUUIDCalled <- true
	m.DeleteGarbanzoByAPIUUIDInput.Ctx <- ctx
	m.DeleteGarbanzoByAPIUUIDInput.ApiUUID <- apiUUID
	return <-m.DeleteGarbanzoByAPIUUIDOutput.Err
}

type mockContext struct {
	DeadlineCalled chan bool
	DeadlineOutput struct {
		Deadline chan time.Time
		Ok       chan bool
	}
	DoneCalled chan bool
	DoneOutput struct {
		Ret0 chan (<-chan struct{})
	}
	ErrCalled chan bool
	ErrOutput struct {
		Ret0 chan error
	}
	ValueCalled chan bool
	ValueInput  struct {
		Key chan interface{}
	}
	ValueOutput struct {
		Ret0 chan interface{}
	}
}

func newMockContext() *mockContext {
	m := &mockContext{}
	m.DeadlineCalled = make(chan bool, 100)
	m.DeadlineOutput.Deadline = make(chan time.Time, 100)
	m.DeadlineOutput.Ok = make(chan bool, 100)
	m.DoneCalled = make(chan bool, 100)
	m.DoneOutput.Ret0 = make(chan (<-chan struct{}), 100)
	m.ErrCalled = make(chan bool, 100)
	m.ErrOutput.Ret0 = make(chan error, 100)
	m.ValueCalled = make(chan bool, 100)
	m.ValueInput.Key = make(chan interface{}, 100)
	m.ValueOutput.Ret0 = make(chan interface{}, 100)
	return m
}
func (m *mockContext) Deadline() (deadline time.Time, ok bool) {
	m.DeadlineCalled <- true
	return <-m.DeadlineOutput.Deadline, <-m.DeadlineOutput.Ok
}
func (m *mockContext) Done() <-chan struct{} {
	m.DoneCalled <- true
	return <-m.DoneOutput.Ret0
}
func (m *mockContext) Err() error {
	m.ErrCalled <- true
	return <-m.ErrOutput.Ret0
}
func (m *mockContext) Value(key interface{}) interface{} {
	m.ValueCalled <- true
	m.ValueInput.Key <- key
	return <-m.ValueOutput.Ret0
}
