#!/usr/bin/env bash

set -e

cd $(dirname $0)/..

IMAGE=$1
MAIN_PATH=$2

IMAGE_DIR=tmp/$IMAGE/image/

mkdir -p $IMAGE_DIR/
cp -r docker/$IMAGE/ $IMAGE_DIR/
mv $IMAGE_DIR/Dockerfile tmp/$IMAGE/

GOOS=linux GOARCH=amd64 go build -o $IMAGE_DIR/$IMAGE $MAIN_PATH
docker build -t myshkin5/$IMAGE:latest tmp/$IMAGE/
