#!/usr/bin/env bash

set -e

cd $(dirname $0)/..

IMAGE_DIR=tmp/docker-image

mkdir -p $IMAGE_DIR/persistence/ddl/
cp persistence/ddl/* $IMAGE_DIR/persistence/ddl/
cp Dockerfile tmp/

GOOS=linux GOARCH=amd64 go build -o $IMAGE_DIR/effective-octo-garbanzo github.com/myshkin5/effective-octo-garbanzo/api

docker build -t myshkin5/effective-octo-garbanzo:latest tmp/
